pub const AUTOPILOT_COMPONENT_ID: u8 = 1;
pub const CAMERA_COMPONENT_ID: u8 = 100;
pub const GIMBAL_COMPONENT_ID: u8 = 154;

pub const MAV_TYPE_FIXED_WING: u8 = 1;
pub const MAV_TYPE_QUADROTOR: u8 = 2;
pub const MAV_TYPE_HELICOPTER: u8 = 4;
pub const MAV_TYPE_GIMBAL: u8 = 26;
pub const MAV_TYPE_CAMERA: u8 = 30;

pub const MAV_AUTOPILOT_GENERIC: u8 = 0;
pub const MAV_AUTOPILOT_INVALID: u8 = 8;

pub const MAV_STATE_STANDBY: u8 = 3;
pub const MAV_STATE_ACTIVE: u8 = 4;

pub const MAV_MODE_FLAG_CUSTOM_MODE_ENABLED: u8 = 1;
pub const MAV_MODE_FLAG_SAFETY_ARMED: u8 = 128;
pub const MAV_LANDED_STATE_UNDEFINED: u8 = 0;
pub const MAV_LANDED_STATE_ON_GROUND: u8 = 1;
pub const MAV_LANDED_STATE_IN_AIR: u8 = 2;

pub const MAV_PROTOCOL_CAPABILITY_MISSION_INT: u64 = 4;
pub const MAV_PROTOCOL_CAPABILITY_COMMAND_INT: u64 = 8;
pub const MAV_PROTOCOL_CAPABILITY_FTP: u64 = 32;
pub const MAV_PROTOCOL_CAPABILITY_SET_POSITION_TARGET_GLOBAL_INT: u64 = 256;
pub const MAV_PROTOCOL_CAPABILITY_MAVLINK2: u64 = 8192;
pub const MAV_PROTOCOL_CAPABILITY_COMPONENT_IMPLEMENTS_GIMBAL_MANAGER: u64 = 262_144;

pub const CAMERA_CAP_FLAGS_HAS_VIDEO_STREAM: u32 = 256;
pub const VIDEO_STREAM_STATUS_FLAGS_RUNNING: u16 = 1;
pub const VIDEO_STREAM_TYPE_RTSP: u8 = 0;
pub const VIDEO_STREAM_TYPE_RTPUDP: u8 = 1;
pub const VIDEO_STREAM_TYPE_TCP_MPEG: u8 = 2;
pub const VIDEO_STREAM_TYPE_MPEG_TS: u8 = 3;
pub const VIDEO_STREAM_ENCODING_H264: u8 = 1;
