author = "ARMATAK Team"
mainprefix = "armatak"
name = "ARMA Team Awareness Kit"
prefix = "armatak"

[version]
build = 0
major = 1
minor = 1 
patch = 0

git_hash = 0

[files]
exclude = [
  "source/*",
  "*.png",
  "*.tga",
  "*.psd",
  "*.fbx",
  "*.obj",
]

include = [
  "LICENSE",
  "*.dll",
  "*.so",
  "*.paa"
]

[properties]
author = "ARMATAK Team"
url = "https://github.com/valmojr/armatak"

[hemtt.config]
preset = "Hemtt"

[hemtt.launch.default]
workshop = [
  "450814997", # CBA_A3
  "463939057", # ace
  "751965892", # ACRE2
  "2522638637", # ACE3 Arsenal Extended - Core
  "333310405", # Enhanced Movement
  "2034363662", # Enhanced Movement Rework
  "843577117", # RHSUSAF
  "3147473073", # TOTT Core
  "623475643", # 3den Enhanced
  "520618345", # Jbad
  "1779063631", # Zeus Enhanced
  "2397360831", # USAF Mod - Main
  "2397376046", # USAF Mod - Utility
  "3147476552", # TOTT Optics
  "583496184", # CUP Terrains - Core
  "2560276469", # Restrict Markers
  "1858075458", # LAMBS_Danger.fsm
  "3407948300", # JSRS SOUNDMOD 2025
  "2834576684", # ITN - Illuminate The Night
  "3375788189", # Immersion Cigs - Rewrite
  "2095827925", # Brighter Flares
  "2257686620", # Blastcore Murr Edition
  "2260572637", # BettIR NVG
  "3493557838", # Broad Spectrum Warfare
  "1291778160", # Hellanmaa
  "3533734689", # FPV
]

parameters = [
  "-skipIntro",
  "-noSplash",
  "-showScriptErrors",
  "-debug",
  "-filePatching",
]

[binarize]
exclude = [
  "*.jpg"
]