[package]
name = "armatak"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arma-rs = "1.10.4"
serde = { version = "1.0.210", features = ["derive"] }

[lib]
name = "armatak"
crate-type = ["cdylib"]
